[build]
  publish = "."
  command = ""

[headers]
  # Set HSTS for Netlify
  [[headers]]
  for = "/*"
    [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
